terraform {
  required_version = ">= 1.5"
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.4"
    }
  }
}

# Simulates a "server config file" being provisioned
resource "local_file" "app_config" {
  filename = "${path.module}/output/app.config"
  content  = <<-EOT
    # App configuration — generated by Terraform
    APP_NAME=${var.app_name}
    APP_PORT=${var.app_port}
    ENVIRONMENT=${var.environment}
    DOCKER_IMAGE=${var.docker_image}
  EOT
}

resource "local_file" "deploy_script" {
  filename        = "${path.module}/output/deploy.sh"
  file_permission = "0755"
  content         = <<-EOT
    #!/bin/bash
    echo "Deploying ${var.app_name} to ${var.environment}..."
    docker pull ${var.docker_image}
    docker stop app 2>/dev/null || true
    docker rm   app 2>/dev/null || true
    docker run -d --name app -p ${var.app_port}:5000 ${var.docker_image}
    echo "Deployment complete."
  EOT
}